name = "bun-hono-api"
main = "server.ts"
compatibility_date = "2024-09-23"

# Use the latest Workers runtime
compatibility_flags = ["nodejs_compat"]

# Define your environment variables (placeholders only, actual values set in Cloudflare dashboard)
[vars]
PORT = "8000"
# Commented out secrets that should be set via wrangler secret commands
# MONGO_URI = "" # Set this as a secret
# JWT_SECRET = "" # Set this as a secret

# For KV storage if needed
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"