name = "bun-hono-api"
main = "server.ts"
compatibility_date = "2024-09-23"

# Use the latest Workers runtime
compatibility_flags = ["nodejs_compat"]

# Define your environment variables
[vars]
# Add your environment variables here, but don't add sensitive ones
# For sensitive variables, use Cloudflare's secret management

# For KV storage if needed
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"